name: shoecloud
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #网络请求库dio
  dio: ^5.9.1
  #轮播图库carousel_slider
  carousel_slider: ^5.1.1

  #nfc库，放弃了nfc_manager，改用flutter_nfc_kit
  #前者过于底层，还得自己处理NDEF格式的数据，这不是我们想要的
  ndef: ^0.4.0
  flutter_nfc_kit: ^3.6.2
  #app_links库，用于处理应用内链接跳转
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/bottom_nav/
    - lib/assets/home/
    - lib/assets/social/
    - lib/assets/my/
